{{
   config(
     materialized='table'
   )
}}
 
SELECT CHANGEAUDITSTAMPS,
       CREATED_TIME,
       CURRENCY,
       ID,
       LAST_MODIFIED_TIME, 
       NAME,
       NOTIFIEDONCAMPAIGNOPTIMIZATION,
       NOTIFIEDONCREATIVEAPPROVAL,
       NOTIFIEDONCREATIVEREJECTION,
       NOTIFIEDONENDOFCAMPAIGN,
       NOTIFIED_ON_NEW_FEATURES_ENABLED,
       REFERENCE,
       REFERENCE_ORGANIZATION_ID,
       REFERENCE_PERSON_ID,
       SERVING_STATUSES,
       STATUS,
       TEST,
       TOTAL_BUDGET,
       TOTAL_BUDGET_ENDS_AT,
       TYPE,
       VERSION
FROM {{ source('tap_linkedin', 'accounts') }} as account_history
