SELECT
    creative_id,
    day,
    actionclicks AS action_clicks,
    adunitclicks AS ad_unit_clicks,
    approximateuniqueimpressions AS approximate_unique_impressions,
    cardclicks AS card_clicks,
    cardimpressions AS card_impressions,
    clicks,
    commentlikes AS comment_likes,
    comments,
    companypageclicks AS company_page_clicks,
    conversionvalueinlocalcurrency AS conversion_value_in_local_currency,
    costinlocalcurrency AS cost_in_local_currency,
    costinusd AS cost_in_usd,
    externalwebsiteconversions AS external_website_conversions,
    externalwebsitepostclickconversions AS external_website_post_click_conversions,
    externalwebsitepostviewconversions AS external_website_post_view_conversions,
    follows,
    fullscreenplays AS full_screen_plays,
    impressions,
    landingpageclicks AS landing_page_clicks,
    leadgenerationmailcontactinfoshares AS lead_generation_mail_contact_info_shares,
    leadgenerationmailinterestedclicks AS lead_generation_mail_interested_clicks,
    likes,
    oneclickleadformopens AS one_click_lead_form_opens,
    oneclickleads AS one_click_leads,
    opens,
    otherengagements AS other_engagements,
    sends,
    shares,
    texturlclicks AS text_url_clicks,
    totalengagements AS total_engagements,
    videocompletions AS video_completions,
    videofirstquartilecompletions AS video_first_quartile_completions,
    videomidpointcompletions AS video_midpoint_completions,
    videothirdquartilecompletions AS video_third_quartile_completions,
    videostarts AS video_starts,
    videoviews AS video_views,
    viralcardclicks AS viral_card_clicks,
    viralcardimpressions AS viral_card_impressions,
    viralclicks AS viral_clicks,
    viralcommentlikes AS viral_comment_likes,
    viralcomments AS viral_comments,
    viralcompanypageclicks AS viral_company_page_clicks,
    viralexternalwebsiteconversions AS viral_external_website_conversions,
    viralexternalwebsitepostclickconversions AS viral_external_website_post_click_conversions,
    viralexternalwebsitepostviewconversions AS viral_external_website_post_view_conversions,
    viralfollows AS viral_follows,
    viralfullscreenplays AS viral_full_screen_plays,
    viralimpressions AS viral_impressions,
    virallandingpageclicks AS viral_landing_page_clicks,
    virallikes AS viral_likes,
    viraloneclickleadformopens AS viral_one_click_lead_form_opens,
    viraloneclickleads AS viral_one_click_leads,
    viralotherengagements AS viral_other_engagements,
    viralshares AS viral_shares,
    viraltotalengagements AS viral_total_engagements,
    viralvideocompletions AS viral_video_completions,
    viralvideofirstquartilecompletions AS viral_video_first_quartile_completions,
    viralvideomidpointcompletions AS viral_video_midpoint_completions,
    viralvideostarts AS viral_video_starts,
    viralvideothirdquartilecompletions AS viral_video_third_quartile_completions,
    viralvideoviews AS viral_video_views,
    _sdc_batched_at

FROM {{ source('tap_linkedin', 'ad_analytics_by_creative') }}
