{{
   config(
     materialized='table'
   )
}}

SELECT ACCOUNT,
       ACCOUNT_ID,
       ASSOCIATED_ENTITY,
       ASSOCIATED_ENTITY_ORGANIZATION_ID,
       ASSOCIATED_ENTITY_PERSON_ID,
       AUDIENCE_EXPANSION_ENABLED,
       CAMPAIGN_GROUP,
       CAMPAIGN_GROUP_ID,
       CHANGE_AUDIT_STAMPS,
       COST_TYPE,
       CREATED_TIME,
       CREATIVE_SELECTION,
       DAILY_BUDGET,
       FORMAT,
       ID,
       LAST_MODIFIED_TIME,
       LOCALE,
       NAME,
       OBJECTIVE_TYPE,
       OFFSITE_DELIVERY_ENABLED,
       OFFSITE_PREFERENCES,
       OPTIMIZATION_TARGET_TYPE,
       PACING_STRATEGY,
       RUN_SCHEDULE,
       SERVING_STATUSES,
       STATUS,
       TARGETING,
       TARGETING_CRITERIA,
       TEST,
       TOTAL_BUDGET,
       TYPE,
       UNIT_COST,
       VERSION,
       VERSION_TAG
FROM {{ source('tap_linkedin', 'campaign') }} as campaign_history
