{{
   config(
     materialized='table'
   )
}}

SELECT ID,
LAST_MODIFIED_AT,
CALL_TO_ACTION,
CLICK_URI,
REFERENCE,
FOLLOWER_LOGO,
FOLLOWER_SHOW_MEMBER_PROFILE_PHOTO,
FOLLOWER_ORGANIZATION_NAME,
TEXT_AD_HEADLINE,
TEXT_AD_DESCRIPTION,
TEXT_AD_IMAGE,
JOBS_ORGANIZATION_NAME,
JOBS_LOGO,
JOBS_SHOW_MEMBER_PROFILE_PHOTO,
SPOTLIGHT_DESCRIPTION,
SPOTLIGHT_HEADLINE,
SPOTLIGHT_LOGO,
SPOTLIGHT_ORGANIZATION_NAME,
SPOTLIGHT_SHOW_MEMBER_PROFILE_PHOTO,
CREATED_AT,
CREATED_BY,
INTENDED_STATUS,
INLINE_CONTENT,
IS_SERVING,
LAST_MODIFIED_BY,
REVIEW_STATUS,
CAMPAIGN_ID,
ACCOUNT_ID,
_SDC_BATCHED_AT

FROM {{ source('tap_linkedin', 'creatives') }} as creative_history